# Uncomment the next line to define a global platform for your project
  platform :ios, '15.1'

target 'singleLoginApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for singleLoginApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'IQKeyboardManagerSwift'
end
